# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 691a8521a10064563786f2ba768c54f7590811b8e61da15a93e855bd846d08d9139f022a17691bc045fbca714b9ae53d606cfab5b9eefb52bfc19f22cf69eb39

test:
  secret_key_base: 7a1c183efc335c742aa5c38d491d983e0c6996fff45960cc609e66b52d698cc39156940f0adcbd169a98b2daa003a8053c0b28f2f5c200e977631d70dfdcefcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
